### ISSUE TITLE
Won't save

### ISSUE THREAD

**Issue by AzBat360** [dtjm/textdropapp.com#108] opened 2012-05-05 01:46 UTC
On free version(2.2.3) the "Save" button greys out & says "Saving", but never saves the file or say "Saved". It does this manually or using Autosave.

**Comment by dtjm** [comment] 2012-05-05 03:35
Hi, looks like some software got changed on my server behind my back. Thanks for letting me know.

[edit - I'm looking at it, but I'm not sure when it will be fixed]

**Comment by dtjm** [comment] 2012-05-05 15:50
I can't seem to figure out what the issue is. Please try https://write-box.appspot.com/ or http://dillinger.io/ for now until I can fix it. I haven't used those apps but they offer a similar free service to TextDrop.

**Comment by AzBat360** [comment] 2012-05-05 19:15
No problem. Thanks for the follow-up & the suggestions. I'll keep checking in for the status.

**Comment by AzBat360** [comment] 2012-05-05 20:23
Checked out Writebox. It's definitely a worthy replacement of TextDrop. Sorry. It even has a few extra features that your free version doesn't have. I'll keep checking out your version, but can't guarantee I will go back to using it full-time. Wish you the best & thanks for the great app & support.

**Comment by dtjm** [comment] 2012-05-05 20:29
No need to apologize...I don't really have time to keep up the free version so I'm glad you were able to find something that works for you.  I almost certainly won't be adding any new features anyways, so it's sort of at a dead-end right now.

Cheers,
/sam

**Comment by dtjm** [comment] 2012-05-06 17:48
Looks like a cookie issue. Access the site from now on at http://textdrop2.herokuapp.com

**Closed as completed by dtjm** 2012-05-06 17:48 UTC
Labels: bug

**Comment by AzBat360** [comment] 2012-05-06 18:46
Thanks!
